# Generated by Django 4.2.7 on 2024-09-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diagnosis', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('medicines', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescription',
                'ordering': ['-created_at'],
            },
        ),
    ]
