# Generated by Django 4.2.7 on 2024-09-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'role')},
        ),
    ]
